apiVersion: v1
kind: Service
metadata:
  name: sample-green
spec:
  selector:
    app: sample
    version: green
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP