apiVersion: v1
kind: Service
metadata:
  name: sample-blue
spec:
  selector:
    app: sample
    version: blue
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
